### ISSUE TITLE
UI bug on the Reward Panel

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-rewards-ios#132]
The text is a bit jumpy

![Bug](https://user-images.githubusercontent.com/7606853/61077987-6b4b4500-a3d4-11e9-9110-cb3bbce71bff.gif)

**Comment by kylehickinson** [comment]
I actually know the source of this issue, and I'm not sure if I can fix it as its part of the iOS framework

iOS dev explanation: 
The popover is given `additionalSafeAreaInsets` based on the arrow so that the content can bleed into the arrow. This means that we constrain our views to the `safeAreaLayoutGuide`.  However, for some reason iOS applies these constraints even when rotated, so when you rotate it so that the center-y origin of moves passed the safe area, it actually begins to push it down to remain constrained correctly.

Not sure how we can fix this aside from making our own layout guide instead of using safeAreaLayoutGuide which seems to act differently?

**Comment by anthonypkeane** [comment]
Leaving out of MVP, but please add back in if there is time at the end.
It is pretty bad.
